# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stubs/microservice_b.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stubs/microservice_b.proto',
  package='Transaction',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1astubs/microservice_b.proto\x12\x0bTransaction\x1a\x1cgoogle/protobuf/struct.proto\"$\n\x14GetAudioChunkRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"A\n\x15GetAudioChunkResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x17\n\x0f\x45xceptionString\x18\x02 \x01(\t2m\n\x0c\x41udioService\x12]\n\x12GetAudioChunkValue\x12!.Transaction.GetAudioChunkRequest\x1a\".Transaction.GetAudioChunkResponse(\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_GETAUDIOCHUNKREQUEST = _descriptor.Descriptor(
  name='GetAudioChunkRequest',
  full_name='Transaction.GetAudioChunkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Transaction.GetAudioChunkRequest.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=109,
)


_GETAUDIOCHUNKRESPONSE = _descriptor.Descriptor(
  name='GetAudioChunkResponse',
  full_name='Transaction.GetAudioChunkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Success', full_name='Transaction.GetAudioChunkResponse.Success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ExceptionString', full_name='Transaction.GetAudioChunkResponse.ExceptionString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['GetAudioChunkRequest'] = _GETAUDIOCHUNKREQUEST
DESCRIPTOR.message_types_by_name['GetAudioChunkResponse'] = _GETAUDIOCHUNKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAudioChunkRequest = _reflection.GeneratedProtocolMessageType('GetAudioChunkRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAUDIOCHUNKREQUEST,
  '__module__' : 'stubs.microservice_b_pb2'
  # @@protoc_insertion_point(class_scope:Transaction.GetAudioChunkRequest)
  })
_sym_db.RegisterMessage(GetAudioChunkRequest)

GetAudioChunkResponse = _reflection.GeneratedProtocolMessageType('GetAudioChunkResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETAUDIOCHUNKRESPONSE,
  '__module__' : 'stubs.microservice_b_pb2'
  # @@protoc_insertion_point(class_scope:Transaction.GetAudioChunkResponse)
  })
_sym_db.RegisterMessage(GetAudioChunkResponse)



_AUDIOSERVICE = _descriptor.ServiceDescriptor(
  name='AudioService',
  full_name='Transaction.AudioService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAudioChunkValue',
    full_name='Transaction.AudioService.GetAudioChunkValue',
    index=0,
    containing_service=None,
    input_type=_GETAUDIOCHUNKREQUEST,
    output_type=_GETAUDIOCHUNKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIOSERVICE)

DESCRIPTOR.services_by_name['AudioService'] = _AUDIOSERVICE

# @@protoc_insertion_point(module_scope)
