# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stubs import microservice_b_pb2 as stubs_dot_microservice__b__pb2


class AudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAudioChunkValue = channel.stream_unary(
                '/Transaction.AudioService/GetAudioChunkValue',
                request_serializer=stubs_dot_microservice__b__pb2.GetAudioChunkRequest.SerializeToString,
                response_deserializer=stubs_dot_microservice__b__pb2.GetAudioChunkResponse.FromString,
                )


class AudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAudioChunkValue(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAudioChunkValue': grpc.stream_unary_rpc_method_handler(
                    servicer.GetAudioChunkValue,
                    request_deserializer=stubs_dot_microservice__b__pb2.GetAudioChunkRequest.FromString,
                    response_serializer=stubs_dot_microservice__b__pb2.GetAudioChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transaction.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAudioChunkValue(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Transaction.AudioService/GetAudioChunkValue',
            stubs_dot_microservice__b__pb2.GetAudioChunkRequest.SerializeToString,
            stubs_dot_microservice__b__pb2.GetAudioChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
