# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from stubs import second_service_pb2 as stubs_dot_second__service__pb2


class AudioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAudioChunkValue = channel.unary_unary(
                '/Audio.Audio/GetAudioChunkValue',
                request_serializer=stubs_dot_second__service__pb2.GetAudioChunkRequest.SerializeToString,
                response_deserializer=stubs_dot_second__service__pb2.GetAudioChunkResponse.FromString,
                )


class AudioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAudioChunkValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAudioChunkValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudioChunkValue,
                    request_deserializer=stubs_dot_second__service__pb2.GetAudioChunkRequest.FromString,
                    response_serializer=stubs_dot_second__service__pb2.GetAudioChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Audio.Audio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Audio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAudioChunkValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Audio.Audio/GetAudioChunkValue',
            stubs_dot_second__service__pb2.GetAudioChunkRequest.SerializeToString,
            stubs_dot_second__service__pb2.GetAudioChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
